# Generated by Django 4.0.4 on 2022-04-25 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FlightReservationAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'verbose_name': 'Flight'},
        ),
        migrations.AlterModelOptions(
            name='passenger',
            options={'verbose_name': 'Passenger'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Reservation'},
        ),
    ]
